# Generated by Django 3.2.13 on 2022-05-31 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20220531_2046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='name',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='slug',
        ),
        migrations.AddField(
            model_name='tag',
            name='title',
            field=models.CharField(default='Value', max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
